class MedicationDatabase {
    static const List<String> medicamentos = [
      'Paracetamol',
      'Ibuprofeno',
      'Amoxicilina',
      'Omeprazol',
      'Simvastatina',
      'Enalapril',
      'Metformina',
      'Atorvastatina',
      'Losartan',
      'Sertralina',
      'Ciprofloxacina',
      'Clonazepam',
      'Diazepam',
      'Ranitidina',
      'Sinvastatina',
      'Tramadol',
      'Pantoprazol',
      'Codeína',
      'Fluoxetina',
      'Hidroclorotiazida',
      'Lorazepam',
      'Prednisolona',
      'Amoxicilina + Ácido Clavulânico',
      'Escitalopram',
      'Bromazepam',
      'Duloxetina',
      'Paroxetina',
      'Metronidazol',
      'Lansoprazol',
      'Venlafaxina',
      'Alprazolam',
      'Cetirizina',
      'Rosuvastatina',
      'Tamsulosina',
      'Levetiracetam',
      'Cloridrato de Sotalol',
      'Cloridrato de Bupropiona',
      'Bisoprolol',
      'Travoprost',
      'Amitriptilina',
      'Nifedipina',
      'Metotrexato',
      'Levotiroxina',
      'Cloridrato de Propranolol',
      'Gliclazida',
      'Cloridrato de Ciprofloxacina',
      'Budesonida',
      'Carvedilol',
      'Dorzolamida',
      'Furosemida'
    ];
}